# Generated by Django 4.1.4 on 2022-12-23 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_history_language_softskill_techskill_myinfo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ("-added_at",)},
        ),
    ]
